### ISSUE TITLE
Running the ftpserver command throws up warning 

### ISSUE THREAD

**Issue by manuganji** [tokibito/django-ftpserver#11]
I got this error when I ran `python manage.py ftpserver 10021` as per your documentation

`RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)
`

It also threw `OSError: [Errno 13] Permission denied
` error. How to handle it?

**Comment by bufke** [comment]
The permission denied is a separate and unrelated issue I think. With Django 1.10 on RC1 it would be nice to add compatibility. I might send a pull request if I have time.

**Comment by bufke** [comment]
The fix is going to break django<1.7. @tokibito what do you want to do here? I'd be willing to add 1.10 support with a unit test showing how it breaks but I'm not willing to provide backwards compatibility. Django extensions uses [this](https://github.com/thecardcheat/django-extensions/blob/160aaa80829a9e2cd45ff00d7054e9bb09393b98/django_extensions/compat.py#L211) for compatibility.

**Comment by tokibito** [comment]
fixed. Thanks @bufke .
